### ISSUE TITLE
Fix lint issues

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact_py#1]
`make lint` shows a whole bunch of trivial lint issues that I have yet to address. Would be good to get things documented a little bit and other fixes.

**Comment by vitiral** [comment]
@Josh-Thompson you mentioned you might be interested in starter issues?

**Comment by vitiral** [comment]
Once this is done, it can be added to the general `make check` which will gate on the lints being complete.

**Comment by visceralfield** [comment]
Seems like a great opportunity for me to warm up to the codebase, I'll download the repo tonight and begin.

**Comment by visceralfield** [comment]
As go through these lints, there are a few high-level questions about what might be desirable linter settings. Overall my effort in this branch is simply to directly address the issues described by the lints, but for some I would suggest instead modifying the project lint settings to no longer detect the issue type in question, but this is a larger-level project decision. Specifically, my recommendations thus far, which I'd like to discuss, are to:

- disable the `too-few-public-methods` lint outright, project-wide. This lint is a fairly controversial one, and with good reason in my opinion.

- allow a few shortnames project-wide. Pylint does not like variable names that are 1 or 2 letters long, and I think that overall descriptive names are better, but using a `pylintrc` file a few specific shortnames could be allowed. In the context of lambdas, list comprehensions, and things with genuinely short names, I think giving a few allowed 1 or 2 letter variables names is a good idea. This will still flag a lint if someone writes `def foo(a, b, c, d, e)`, but will allow specific cases.

- use `docstring-min-length` to set a minimum number of lines for a function for pylint to trigger the `missing-docstring` lint. I would recommend, say, 5 lines. Requiring docstrings on extremely short get_x or is_x functions hurts maintainability by requiring duplicated effort every time these short, self-describing functions get updated.

- add https://github.com/jongracecox/pylint-exit to the list of dev packages installed by make init, and use it in the addition of pylint to `make check`.  Pylint uses bit-encoded exit codes and pylint-exit provides a customizable way to decode those exit codes into actual pass-or-fail exit codes.

Let me know your thoughts.

**Comment by vitiral** [comment]
Yes, all those suggestions are great. thanks for doing this.

>

**Comment by vitiral** [comment]
I'm thinking of working on some issues tomorrow. Do you have a branch that we can merge with a first set of changes?

Fixing lint issues can always create lots of small conflicts, so I don't want to make modifications if you are in the middle of any sweeping changes.

**Comment by visceralfield** [comment]
This is my working branch: https://github.com/Josh-Thompson/artifact_py/tree/fix-lint

The submodules I've touched so far are:
- `name`
- `settings`
- `completion`
- `code`
- `__init__`
- `load` (unfinished)

Everything should be good to merge in, but I should stress that I have only been doing static analysis - I still can't `make init` the project, so I haven't run it yet. Some 'unused import' warnings etcetera that I make have taken care of might have actually been false alarms (pylint can be like that) and so you may want to try a quick clone and make of my branch before merging.

**Comment by vitiral** [comment]
I'm picking up your branch and finishing this up. Thanks for the great work!
