### ISSUE TITLE
Add lint module

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact_py#2]
`artifact_py lint` should run lints. The general design is defined at https://github.com/vitiral/artifact_py#SPC-design.lint

The items to complete are:

- [x] partof links that do not exist
- [x] A REQ or SPC being partof a TST
- [x] Extra impl links in code (`project.impls` dict[str, list]` for this reason)
- [x] Having an artifact specified as "done" having an impl
- [x] Artifact or subpart like links in text (i.e. [REQ-does-not-exist]) that do not exist
- [ ] Design docs not being updated (suggest `artifact export --format md -i to fix`).
- ~~[ ] A link being found in code that does not have the doc_url prefixed. (i.e. artifact expects links in code to look like myurl.com/design#REQ-foo). This will need a new setting like `doc_url`~~

This can be done in separate PRs or several combined into a single.

**Comment by vitiral** [comment]
@Josh-Thompson any of these would also be good first issues!

The basic design is just a function `lint_project(project)` in `lint.py` which adds to an `errors` list and returns that list at the end.

**Comment by visceralfield** [comment]
Will try this out after looking at #1
